// <auto-generated />
using System;
using EventBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventBooking.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908165202_V2CleanupDraft")]
    partial class V2CleanupDraft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CateringMenuId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<int>("HallSlotId")
                        .HasColumnType("integer");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CateringMenuId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("HallSlotId", "Status");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.BookingExtraService", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("PriceAtBooking")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("BookingId", "ExtraServiceId");

                    b.HasIndex("ExtraServiceId");

                    b.ToTable("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.CateringMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IncludesDrinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerGuest")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("CateringMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full meat menu, first course to dessert.",
                            IncludesDrinks = true,
                            IsActive = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Meat Menu",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            PricePerGuest = 220m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dairy and fish menu.",
                            IncludesDrinks = true,
                            IsActive = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Dairy Menu",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            PricePerGuest = 180m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fully plant-based menu.",
                            IncludesDrinks = false,
                            IsActive = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Vegan Menu",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            PricePerGuest = 160m
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Wedding"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Bar Mitzvah"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Bat Mitzvah"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Corporate Event"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Birthday"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Private Event"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.EventTypeServiceCategory", b =>
                {
                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("EventTypeId", "ServiceCategoryId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("EventTypeServiceCategories");

                    b.HasData(
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 1,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 2,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 3,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 4,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 4,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 4,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 4,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 4,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 5,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 6,
                            ServiceCategoryId = 8
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            EventTypeId = 7,
                            ServiceCategoryId = 8
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Pricing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("UnitLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Open bar, cocktails and soft drinks.",
                            IsActive = true,
                            Name = "Premium Bar Package",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Price = 90m,
                            Pricing = "PerGuest",
                            ServiceCategoryId = 8,
                            UnitLabel = "per guest"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Floral Centerpieces",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Price = 180m,
                            Pricing = "Flat",
                            ServiceCategoryId = 6,
                            UnitLabel = "per table"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Live Band",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Price = 8000m,
                            Pricing = "Flat",
                            ServiceCategoryId = 5,
                            UnitLabel = "per event"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Photography",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Price = 5000m,
                            Pricing = "Flat",
                            ServiceCategoryId = 4,
                            UnitLabel = "per event"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 400,
                            Name = "Main Ballroom",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 150,
                            Name = "Garden Hall",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 300,
                            Name = "Crystal Hall",
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HallId")
                        .HasColumnType("integer");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "Date", "Shift")
                        .IsUnique();

                    b.ToTable("HallSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 6000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Morning",
                            Status = "Available",
                            Version = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 9000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Noon",
                            Status = "Available",
                            Version = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 15000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 15000m,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 8000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 2,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 10000m,
                            Date = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 3,
                            Shift = "Noon",
                            Status = "Available",
                            Version = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 16000m,
                            Date = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 3,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Catering",
                            IsActive = true,
                            Name = "Catering"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TableDesign",
                            IsActive = true,
                            Name = "Table Design"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BridalChair",
                            IsActive = true,
                            Name = "Bridal Chair"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Photography",
                            IsActive = true,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 5,
                            Code = "DJ",
                            IsActive = true,
                            Name = "DJ / Music"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Flowers",
                            IsActive = true,
                            Name = "Flowers"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Lighting",
                            IsActive = true,
                            Name = "Lighting"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Other",
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "System Admin",
                            Email = "admin@eventbooking.local",
                            PasswordHash = "$2a$12$./ujlozjB7mpUpkNuPnKxOQEuUb/FVNPvZ1qYkSDWAD5Af8Sn0JtC",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo Manager",
                            Email = "manager@eventbooking.local",
                            PasswordHash = "$2a$12$./ujlozjB7mpUpkNuPnKxOQEuUb/FVNPvZ1qYkSDWAD5Af8Sn0JtC",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo Customer",
                            Email = "client@eventbooking.local",
                            PasswordHash = "$2a$12$./ujlozjB7mpUpkNuPnKxOQEuUb/FVNPvZ1qYkSDWAD5Af8Sn0JtC",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rehov Malchei Yisrael 12",
                            City = "Jerusalem",
                            ContactPhone = "02-500-1000",
                            Name = "Beit Simcha",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rehov Rabbi Akiva 88",
                            City = "Bnei Brak",
                            ContactPhone = "03-570-2000",
                            Name = "Ganei HaPnina",
                            OwnerUserId = new Guid("b0000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.CateringMenu", "CateringMenu")
                        .WithMany()
                        .HasForeignKey("CateringMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventBooking.Core.Entities.EventType", "EventType")
                        .WithMany("Bookings")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.HallSlot", "HallSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("HallSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.User", "Owner")
                        .WithMany("Bookings")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CateringMenu");

                    b.Navigation("EventType");

                    b.Navigation("HallSlot");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.BookingExtraService", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Booking", "Booking")
                        .WithMany("BookingExtraServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.ExtraService", "ExtraService")
                        .WithMany("BookingExtraServices")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ExtraService");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.CateringMenu", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.User", "Owner")
                        .WithMany("OwnedCateringMenus")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.EventTypeServiceCategory", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.EventType", "EventType")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("EventTypes")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ExtraService", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.User", "Owner")
                        .WithMany("OwnedServices")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Venue", "Venue")
                        .WithMany("Halls")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Hall", "Hall")
                        .WithMany("Slots")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Venue", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.User", "Owner")
                        .WithMany("OwnedVenues")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.Navigation("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.EventType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceCategories");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ExtraService", b =>
                {
                    b.Navigation("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("EventTypes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("OwnedCateringMenus");

                    b.Navigation("OwnedServices");

                    b.Navigation("OwnedVenues");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Venue", b =>
                {
                    b.Navigation("Halls");
                });
#pragma warning restore 612, 618
        }
    }
}
