// <auto-generated />
using System;
using EventBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventBooking.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906202027_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<int>("HallSlotId")
                        .HasColumnType("integer");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("HallSlotId", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.BookingExtraService", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtBooking")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("BookingId", "ExtraServiceId");

                    b.HasIndex("ExtraServiceId");

                    b.ToTable("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UnitLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full meat menu, first course to dessert.",
                            Name = "Catering - Meat Menu",
                            Price = 220m,
                            UnitLabel = "per plate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Floral Centerpieces",
                            Price = 180m,
                            UnitLabel = "per table"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Live Band",
                            Price = 8000m,
                            UnitLabel = "per event"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Photography",
                            Price = 5000m,
                            UnitLabel = "per event"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 400,
                            Name = "Main Ballroom",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 150,
                            Name = "Garden Hall",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 300,
                            Name = "Crystal Hall",
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HallId")
                        .HasColumnType("integer");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "Date", "Shift")
                        .IsUnique();

                    b.ToTable("HallSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 6000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Morning",
                            Status = "Available",
                            Version = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 9000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Noon",
                            Status = "Available",
                            Version = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 15000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 15000m,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 1,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 8000m,
                            Date = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 2,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 10000m,
                            Date = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 3,
                            Shift = "Noon",
                            Status = "Available",
                            Version = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 16000m,
                            Date = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HallId = 3,
                            Shift = "Evening",
                            Status = "Available",
                            Version = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rehov Malchei Yisrael 12",
                            City = "Jerusalem",
                            ContactPhone = "02-500-1000",
                            Name = "Beit Simcha"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rehov Rabbi Akiva 88",
                            City = "Bnei Brak",
                            ContactPhone = "03-570-2000",
                            Name = "Ganei HaPnina"
                        });
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.HallSlot", "HallSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("HallSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.User", "Owner")
                        .WithMany("Bookings")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HallSlot");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.BookingExtraService", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Booking", "Booking")
                        .WithMany("BookingExtraServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Core.Entities.ExtraService", "ExtraService")
                        .WithMany("BookingExtraServices")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ExtraService");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Venue", "Venue")
                        .WithMany("Halls")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.HasOne("EventBooking.Core.Entities.Hall", "Hall")
                        .WithMany("Slots")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Booking", b =>
                {
                    b.Navigation("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.ExtraService", b =>
                {
                    b.Navigation("BookingExtraServices");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Hall", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.HallSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventBooking.Core.Entities.Venue", b =>
                {
                    b.Navigation("Halls");
                });
#pragma warning restore 612, 618
        }
    }
}
